---
# Source: prometheus-adapter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-2.11.0
    release: prometheus-adapter
    heritage: Helm
  name: prometheus-adapter
  namespace: default
