---
# Source: kube-prometheus-stack/templates/grafana/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-stack-grafana
  namespace: default
  labels:
    app: kube-prometheus-stack-grafana
    
    chart: kube-prometheus-stack-12.10.6
    release: "kube-prometheus-stack"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: "kube-prometheus-stack"
  namespaceSelector:
    matchNames:
      - "default"
  endpoints:
  - port: service
    path: "/metrics"
