apiVersion: v1
kind: ConfigMap
metadata:
  name: error-service-nginx-conf
  namespace: podinfo
  labels:
    app: error-service
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }

    http {
      server {
        listen       80;
        server_name  localhost;

        location /healthz {
          access_log off;
          add_header Content-Type application/json;
          return 200 '{"status":"OK"}';
        }

        location /nginx_status {
          access_log off;
          stub_status;
        }

        location / {
          add_header Content-Type application/json;
          return 500 '{"message":"error"}';
        }
      }
    }
