apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: error-service
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: error-service
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: error-service
          servicePort: 80
