apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx
spec:
  groups:
    - name: ingress-nginx
      rules:
        - alert: NGINXTooMany500s
          expr: 100 * ( sum( nginx_ingress_controller_requests{job="ingress-nginx-controller-metrics",status=~"5.+"} ) / sum(nginx_ingress_controller_requests{job="ingress-nginx-controller-metrics"}) ) > 5
          for: 1m
          labels:
            severity: warning
          annotations:
            description: Too many 5XXs
            summary: More than 5% of all requests returned 5XX, this requires your attention
