---
# Source: kube-prometheus-stack/templates/prometheus-operator/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-prometheus-stack-operator
  namespace: default
  labels:
    app: kube-prometheus-stack-operator
    
    chart: kube-prometheus-stack-12.10.6
    release: "kube-prometheus-stack"
    heritage: "Helm"
imagePullSecrets:
  []
