---
# Source: kube-prometheus-stack/templates/prometheus-operator/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-operator
  namespace: default
  labels:
    app: kube-prometheus-stack-operator
    
    chart: kube-prometheus-stack-12.10.6
    release: "kube-prometheus-stack"
    heritage: "Helm"
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: kube-prometheus-stack-operator
    release: "kube-prometheus-stack"
  type: "ClusterIP"
