---
# Source: kube-prometheus-stack/templates/prometheus/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-prometheus
  namespace: default
  labels:
    app: kube-prometheus-stack-prometheus
    self-monitor: "true"
    
    chart: kube-prometheus-stack-12.10.6
    release: "kube-prometheus-stack"
    heritage: "Helm"
spec:
  ports:
  - name: web
    nodePort: 30090
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: kube-prometheus-stack-prometheus
  type: "NodePort"
